### ISSUE TITLE
Enac on top of VUE?

### ISSUE THREAD

**Issue by DQvsRA** [enactjs/enact#1529]
I'm wondering do you have a support or version atop of VUE / VUEX / VUE-Router ?

**Comment by ryanjduffy** [comment]
Thanks for the question, @DQvsRA! Unfortunately, we don't have any current plans to support our components within a Vue app. I think it would be possible to generalize the logic for Enact components in such a way that they could be exposed via any number of frameworks, I would not expect the value to outweigh the complexity of that abstraction.

I don't have much experience with Vue but I think it would be difficult to integrate with Enact in its current form. I spent a little time this morning exploring it and was able to achieve some level of integration using [vuera](https://github.com/akxcv/vuera). The main problem I ran into was integrating the necessary build configurations from Enact into vue (using `create-vue-app`).

Right now, our tooling, [@enact/cli](https://github.com/enact/cli), is full-featured but somewhat specialized to our use cases. As a result, configuring them within another build system can be difficult. We have plans to improve this story but we're not there yet.

For now, Enact works best when using our tooling though you can, in most cases, use other React libraries within an Enact app.

**Comment by DQvsRA** [comment]
@ryanjduffy Thanks for your answer.
