### ISSUE TITLE
Config alias path in Enact

### ISSUE THREAD

**Issue by RichardNTran** [enactjs/enact#1865]
I'm working with WebOS and want to apply resolve alias into project but I don't saw anything about it. I checked Enact Build Options but dont see it

**Comment by JayCanuck** [comment]
Could I get some more information about how/why you'd like this feature?

For the Enact CLI, we tend to adhere pretty closely to create-react-app for compatibility purposes, and ever they don't expose alias config out-of-the-box.  If you are absolutely in need of full webpack config access, it might be work considering [ejecting your app](http://enactjs.com/docs/developer-tools/cli/ejecting-apps/).

**Comment by RichardNTran** [comment]
I want to use the alias config in our project structure. I have to custom something else define a common component in one area and for each special screen we have special component. And when we import component with the path is too far, which make ugly
example: 
import Button from '../../../components/Button';
import i18next from '../../../utils/i18n';

**Comment by RichardNTran** [comment]
Thankyou for your support, maybe I show check and config with enact eject
