### ISSUE TITLE
Apply Router into webOS application

### ISSUE THREAD

**Issue by RichardNTran** [enactjs/enact#1897]
I'm using enact to build TV Application, I'm trying to apply react-router-dom into our project, but it just ok when running the project with the browser. When building to ipk for Smart TV, maybe it can't understand something like "router" or "browser router".
Could you tell me what package should I use to navigate screen page at here?

**Comment by krisnamargono-bbmtek** [comment]
@RichardNTran hello, have you solve the issue? If yes, can you share how you do that? Thank you

**Comment by jikjoo** [comment]
It can be solved by using "HashRouter" as Router instead of "BrowserRouter".

**Comment by RichardNTran** [comment]
Ah thanks, I resolved at longtime. yub right, using HashRouter instead
