### ISSUE TITLE
How to update to enact 2?

### ISSUE THREAD

**Issue by nghiatv** [enactjs/enact#1919]
Im using `@enact/cli` to create new project. But i see in `dependencies` it still version `1.*`

```
                "@enact/core": "^1.15.0",
		"@enact/i18n": "^1.15.0",
		"@enact/moonstone": "^1.15.0",
		"@enact/spotlight": "^1.15.0",
		"@enact/ui": "^1.15.0",
		"@enact/webos": "^1.15.0",
```
How to update it to version 2.x?

**Comment by webOS101** [comment]
If you update to the latest version fo the Enact CLI you should get a more recent version of the libraries.  Try:

```
 npm install -g @enact/cli
```

If you want to update your dependencies manually, you can do:

```
npm install --save @enact/core@^2.1.1 @enact/i18n@^2.1.1 @enact/moonstone@^2.1.1 @enact/spotlight@^2.1.1 @enact/ui@^2.1.1 @enact/webos@^2.1.1 prop-types@^15.6.0 react@^16.3.2 react-dom@^16.3.2
```

That should update your `package.json` and install the latest versions.  You can refer to our [migration guide](http://enactjs.com/docs/developer-guide/migration/enact/migrating-to-enact-2/) for differences between 1.x and 2.x.

**Comment by webOS101** [comment]
Hoping this worked for you.  Please comment or make a new ticket if this did not resolve your issue.
