### ISSUE TITLE
How to serve static file?

### ISSUE THREAD

**Issue by nghiatv** [enactjs/enact#1976]
Hi, I have a problem with static file.

I want to create a placeholder image. 
But i have some question about it.
Where do I put it?
and how to use it with `<img />` tag?

**Comment by JayCanuck** [comment]
Files can be required like javascript files, with their imported value being the outputted filepath, which can be used with any regular `<img />` tag.  Importing/requiring the image file will add it to the files that will be outputted in the build.

For example:
```js
import kind from '@enact/core/kind';
import logo from './logo.png'; // Tell Webpack this JS file uses this image

const MyLogo = kind({
  render: function() {
    // Import result is the URL of your image
    return <img src={logo} alt="Logo" />;
  }
});

export default MyLogo;
```

**Comment by webOS101** [comment]
Don't forget you can drop by our [Gitter channel](https://gitter.im/EnactJS/Lobby) to ask questions!

**Comment by nghiatv** [comment]
@JayCanuck It works. Thank you so much.
@webOS101 I'm sorry I have no knowledge of this before
