### ISSUE TITLE
Enact Moonstone video player not working on Tizen Tv(5.0)

### ISSUE THREAD

**Issue by Sumitha-95** [enactjs/enact#2123]
Hi,
I need to add a video player to my application.I integrated moonstone player for the same.But video is not getting played when I tested on Tizen Tv.But I got it working on emulator though.How can I fix this?

```
 <VideoPlayer ref={this.setVideoRef} spotlightDisabled={false} className={css.player + ' enact-fit'} style ={{width:'auto'}}>
  <Video autoPlay>
   <source src={source} type="video/mp4" style ={{width:'auto'}} />
   </Video>
  </VideoPlayer>
```

**Comment by sugardave** [comment]
Do you get any console errors that might help?  If it plays in the emulator but not on the device, it might be something like a security/permissions thing.  I don't really know anything about Tizen, so it's difficult to say.

**Comment by webOS101** [comment]
Could it be a codec issue?  Does the video play on Tizen using another video player/video tag?

**Comment by webOS101** [comment]
@Sumitha-95 Do you have any more information that could help on this issue or have you resolved it?

**Comment by webOS101** [comment]
Going to close this issue as we have not received any information to debug it.  If you are still having this issue, please re-open.

**Comment by rossman-x** [comment]
Hello, I'm having the same issue, does the enact videoplayer support HEVC or FHD videos ? It is shown in LG supported media: https://webostv.developer.lge.com/discover/specifications/supported-media-formats/
