### ISSUE TITLE
Inconsistent behavior 

### ISSUE THREAD

**Issue by gabrieljerin** [enactjs/enact#2257]
### Category

[ ] Rendering issue

### Description
[//]: # Application works fine and smooth in web browser but when build is deployed to TV, focus to a component and performance of application is very slow as compared to web browser.
Is there any version dependency for the above mentioned issue?

### Environment
[//]:  "@enact/core": "^2.5.1",
	"@enact/i18n": "^2.5.1",
	"@enact/moonstone": "^2.5.1",
	"@enact/spotlight": "^2.0.0",
	"@enact/ui": "^2.5.1"

**Enact version: 1.2.0**
**NPM version: 6.4.1**
**Node version: 10.15.3**

**Comment by JayCanuck** [comment]
For reference, what version of Enact CLI are you using? This can be seen from the `enact -v` command.

**Comment by webOS101** [comment]
Hi Gabriel, thanks for the report.  Do you have some sample code that demonstrates the issue?  It may be that something in the application is causing unnecessary re-rendering.  On a desktop-class machine, extra renders have little impact.  On an embedded system, extra renders can have a dramatic impact.  Using strategies that reduce renders (`shouldComponentUpdate` and pure components) are important.  You may want to use some of the tips contained in the [Enact performance guide](http://enactjs.com/docs/developer-guide/performance/).

**Comment by webOS101** [comment]
One other tip:  Using Chrome DevTools' processor slow-down feature can be useful to approximate the performance of embedded systems when developing.

**Comment by gabrieljerin** [comment]
> For reference, what version of Enact CLI are you using? This can be seen from the `enact -v` command.

Enact version: 1.2.0

**Comment by gabrieljerin** [comment]
Thanks for the reply @webOS101. Let me optimize the code and recheck the performance of application. Meanwhile, could you give a suggestion or a tip to customize moonstone components?

**Comment by JayCanuck** [comment]
Hi @gabrieljerin , for Enact 2.x you'll want to use CLI 2.x. It includes a wide arrange of improvements over 1.2.0 and may help. Additionally, with 2.x CLI you can target particular versions of browsers using the [Browserslist format](https://github.com/browserslist/browserslist).

For example, to target [LG webOS TV 4.x](http://webostv.developer.lge.com/discover/specifications/web-engine/), you could set env var `BROWSERSLIST="Chrome 53"` before building, then it will only transpile and polyfill the minimum requirements for Chrome 53 without added bulk/processing.

**Comment by webOS101** [comment]
@gabrieljerin Customization is very easy.  The docs should mention the css classes you can pass in.  I would suggest you visit our [Enact gitter chat](https://gitter.im/EnactJS/Lobby) or open a new issue with a specific question.

**Comment by gabrieljerin** [comment]
Hi @webOS101 , Is there a way to use react life cycle hooks in enact/core/kind ?

**Comment by webOS101** [comment]
@gabrieljerin If this issue has been resolved, can you close this ticket?  If not, please provide more information.  If you found your solution, it would be helpful to share it here.
