### ISSUE TITLE
onToggle type not defined in CheckboxItem

### ISSUE THREAD

**Issue by juooy** [enactjs/enact#2510]
### Category

[ ] Rendering issue
[ ] Crash/Exception
[v] Console error or warning
[ ] CLI issue
[ ] Other

### Description
I'm try use  '@enact/moonstone/CheckboxItem' at developing a Enact Typescript applications.

Document's suggestions use the 'onToogle'.

But, 'onToggle' is not defined in CheckboxItem.
(check https://github.com/enactjs/enact/blob/master/packages/moonstone/CheckboxItem/CheckboxItem.js. line: 61)

please, add type 'onToggle'

### Environment
os : macOS Mojave ( 10.14.5 )
node : 8.16.0
npm : 6.10.3
enact : 2.5.3
test browser : chrome 76.0.3809.100, webos emulator v4.0.0

### Reproduction Code
just follow document with typescript : http://enactjs.com/docs/modules/moonstone/ToggleItem/

### Comments and Screen Shots
<img width="1139" alt="스크린샷 2019-08-21 오후 6 10 20" src="https://user-images.githubusercontent.com/3303368/63419031-06f1bb80-c43f-11e9-9d82-8349323f6ca4.png">

**Comment by webOS101** [comment]
@juooy Thanks for the report!  This is a bit of a deficiency with our HoC config handling when generating typescript types.  We'll try to tackle this before our upcoming 3.0 release.  If you're curious, the issue originates in `ui/Toggleable`.  The toggle callback name is configurable so we don't know for sure what the name will be in advance.  We can probably generate with the defaults as a first step to fixing this problem.

**Comment by webOS101** [comment]
@juooy Please check the latest release of Enact (3.0.0-rc.4).  It should have the corrected typings.  Let me know if you find more issues.
