### ISSUE TITLE
Adding actual icons to the Icon documentation

### ISSUE THREAD

**Issue by ahmad-crossplatform** [enactjs/enact#2613]
### Category

* [ ] New component
* [ ] New feature for existing component
* [ ] Modification of existing component or feature
* [X] Other

### Description
[//]: # (Describe the feature and how you expect it to work)
For the [Icon documentation](https://enactjs.com/docs/modules/moonstone/Icon/)  there is a list of Icons  , however it is hard to find what we are looking for if there is no actually drawing of the icons 
### Alternative Approaches
[//]: # (Are there any other solutions you considered?  Why were those not acceptable?)
Add an image for each icon how it will look .

**Comment by webOS101** [comment]
Hi Ahmad, thanks for the suggestion.  We have a sampler which we'll link to from the main docs site soon.  I'm not sure we can easily fit the icons into the docs but I will see if we can do it.  Also, I'm not sure we currently deploy the icon font to the docs site.  Something to consider, for sure.

**Comment by seunghoh** [comment]
We added the sampler link to the doc site. You can see the all icons and names here https://enactjs.com/sampler/sandstone/?path=/story/sandstone-icon--icon
