### ISSUE TITLE
Adding animation flag for the scroller / vertualList 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [enactjs/enact#2627]
### Category

* [ ] New component
* [x] New feature for existing component
* [ ] Modification of existing component or feature
* [ ] Other

### Description
[//]: # (Describe the feature and how you expect it to work)
The animation for the scroller is smooth and nice. However it comes with some costs like CPU consumption , hard to depend on OnScrollStop to track the last position of the scroller as the use might do any activity while the scroll is scrolling . 

So i would suggest to add a property can be called `isAnimated` which set by default to `true`, so if it set to `false` the `OnScroll` wont be active and only `OnScrollStop` would work and of course the scroller would jump to the position with no animation .

**Comment by 0x64** [comment]
`Scroller` has [`scrollMode`](https://enactjs.com/docs/modules/ui/Scroller/#Scroller.scrollMode) prop so the actual scrolling can be handled by browser with minimal CPU load by JS execution when its value is 'native'. 'native' mode is the default mode for [Sandstone](https://github.com/enactjs/sandstone) also. I recommend using 'native' scroll.

If you want to simply jump with `scrollMode` 'translate', ['animate'](https://enactjs.com/docs/modules/ui/Scroller/#Scroller.cbScrollTo) option is provided. Any programmatic call can be jumping not animating.

For natural user inputs, we don't provide option to opt out scroll animation as it hurts user experiences.
