### ISSUE TITLE
Compatibility with expressJS, reactJS and reactNative

### ISSUE THREAD

**Issue by aldobel** [enactjs/enact#2883]
Hi everyone,
I might know if the libraries in this mention are compatible with libraries like expressJS, ReactJS and ReactNative, so as to develop the same app for iOS, Android and webOS.
Thanks for any reply.

**Comment by seunghoh** [comment]
Hi @aldobel 
I am afraid if I understand your question correctly or not. Do you want to know if Enact components can be compatible with other libs? Would you please refer to our blog page https://medium.com/enact-js/enact-and-interoperability-1bebfd178781 ?
Enact is based on React.
AFAIK, ReactNative supports only Andorid and iOS, not webOS 
Thanks

**Comment by aldobel** [comment]
Hello, thank you for your reply...now I take a look at the blog...thank you very much !!!
