### ISSUE TITLE
Running test from any of the enact samples shows error

### ISSUE THREAD

**Issue by Igor-Vuk** [enactjs/enact#2889]
### Category

* [x] CLI issue
* [x] Other

### Description
Cloning any of the projects from enactjs samples https://github.com/enactjs/samples and running script 
**"test", "test-json", "test-watch"** we get an error in console

```
● Unrecognized CLI Parameters:

  Following options were not recognized:
  ["single-run", "browsers"]

  CLI Options Documentation:
  https://jestjs.io/docs/en/cli.html
```

### Environment
node v14.15.0
npm v6.14.8
jest v26.6.3
Windows 10
browser chrome latest

**Enact version:**
enact 3.0.0

### Reproduction Code
any of the samples here https://github.com/enactjs/samples
I used "pattern-routable-panels"

**Comment by MikyungKim** [comment]
I'm sorry we missed this issue. We'll see what went wrong here. We'll update the progress later on. Thanks!

**Comment by MikyungKim** [comment]
We'll fix this in https://github.com/enactjs/samples/pull/132. Thank you!
