### ISSUE TITLE
enact js Version compatibility issue

### ISSUE THREAD

**Issue by BhanuMathurthi** [enactjs/enact#3179]
**Rendering issue and Console error** 

my lg webos device version was 5.30.4 so I have installed enact js libraries with the 3.2.5 version according to the official documentation enact 3.2.5 version is compatible with webOS 5  

while integrating video player with enact framework,  after launching the app on the LG WebOS device of version 5 with enactjs framework of 3.2.5 version it is giving me this error Uncaught TypeError: (0 , r.forwardCustom) is not a function   and while launching the app on tv, it is splashing the screen and it goes in blank and throwing this error 

### Environment
Chromium Version 68.0.3440.0 (Developer Build) (32-bit)
npm version: v10.1.0
node version: v20.7.0

Enact version:
LG WebOS Device version: 05.30.40
Enact cli version: 6.0.2
 SDK version: "4.9.0"
"@enact/core": "^3.2.5",
"@enact/i18n": "^3.2.5",
"@enact/spotlight": "^3.2.5", 
"@enact/ui": "^3.2.5",
"@enact/webos": "^3.2.5", 
"ilib": "npm:ilib-webos@^14.18.0-webos1, 
"@enact/sandstone": "^2.7.10",

Error: 
Uncaught TypeError: (0 , r.forwardCustom) is not a function

**Comment by BhanuMathurthi** [comment]
> **Rendering issue and Console error**
> 
> my lg webos device version was 5.30.4 so I have installed enact js libraries with the 3.2.5 version according to the official documentation enact 3.2.5 version is compatible with webOS 5
> 
> while integrating video player with enact framework, after launching the app on the LG WebOS device of version 5 with enactjs framework of 3.2.5 version it is giving me this error Uncaught TypeError: (0 , r.forwardCustom) is not a function and while launching the app on tv, it is splashing the screen and it goes in blank and throwing this error
> 
> ### Environment
> Chromium Version 68.0.3440.0 (Developer Build) (32-bit) npm version: v10.1.0 node version: v20.7.0
> 
> Enact version: LG WebOS Device version: 05.30.40 Enact cli version: 6.0.2 SDK version: "4.9.0" "@enact/core": "^3.2.5", "@enact/i18n": "^3.2.5", "@enact/spotlight": "^3.2.5", "@enact/ui": "^3.2.5", "@enact/webos": "^3.2.5", "ilib": "npm:ilib-webos@^14.18.0-webos1, "@enact/sandstone": "^2.7.10",
> 
> Error: Uncaught TypeError: (0 , r.forwardCustom) is not a function

after changing the versions package.json is updated to the latest compatible versions with npm update --save it is updated packages like this 	"dependencies": {
		"@enact/core": "^3.5.0",
		"@enact/i18n": "^3.5.0",
		"@enact/sandstone": "^2.7.10",
		"@enact/spotlight": "^3.5.0",
		"@enact/ui": "^3.5.0",
		"@enact/webos": "^3.5.0",
		"ilib": "^14.4.0",
		"prop-types": "^15.8.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"web-vitals": "^3.5.0"
	}, now after making all these changes i have launched the app on lg webos device now it is throwing a different error 
![Screenshot 2023-09-30 121149](https://github.com/enactjs/enact/assets/105037736/68cfe252-2c9a-4526-8419-9a47341f49df)

**Comment by juwonjeong** [comment]
@BhanuMathurthi, It looks like there is a version mismatching issue. @enact/sandstone 2.7.10 version needs to be matched with enact version 4. If you use enact 3.5.0 version, @enact/sandstone 1.5.1 version will be matched. Thank you.

**Comment by seunghoh** [comment]
@BhanuMathurthi I highly recommend using the latest Enact and Sandstone version. As you already pointed out the latest Sandstone, you also need to point out the latest Enact. Would you please refer to the migration guide? Enact 3.X is quite old
https://enactjs.com/docs/developer-guide/migration/enact/migrating-to-enact-4/
https://enactjs.com/docs/developer-guide/migration/enact/migrating-to-enact-4.5/

**Comment by seunghoh** [comment]
Close this issue as no further discussion. Please create an issue again if necessary.
