### ISSUE TITLE
Problems when using the VideoJS Player in enact.

### ISSUE THREAD

**Issue by Hmelevschi1980** [enactjs/enact#3226]
### When using VideoJS Player, I get an error connecting the heart rate module specified in the documentation. import videojs from "video.js"; import "video.js/dist/video-js.css";

###Error: 

ERROR in ./node_modules/video.js/dist/video-js.css (C:\Users\SomeUser\AppData\Roaming\npm\node_modules\@enact\cli\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[1].oneOf[2].use[1]!C:\Users\SomeUser\AppData\Roaming\npm\node_modules\@enact\cli\node_modules\postcss-loader\dist\cjs.js??ruleSet[1].rules[1].oneOf[2].use[2]!C:\Users\SomeUser\AppData\Roaming\npm\node_modules\@enact\cli\node_modules\source-map-loader\dist\cjs.js!./node_modules/video.js/dist/video-js.css)

Module build failed (from C:\Users\SomeUser\AppData\Roaming\npm\node_modules\@enact\cli\node_modules\postcss-loader\dist\cjs.js):
SyntaxError

(1:27) postcss-resolution-independence: <css input> Unknown word

> 1 | data:application/font-woff;charset=utf-8;base64,(many characters)    |                           ^

### Code

```
import React, { useEffect, useState } from "react";
import videojs from "video.js";
import "video.js/dist/video-js.css";

export const VideoJS = (props) => {
  const videoRef = React.useRef(null);
  const playerRef = React.useRef(null);
  const { options, onReady } = props;

  React.useEffect(() => {
    // Make sure Video.js player is only initialized once
    if (!playerRef.current) {
      // The Video.js player needs to be _inside_ the component el for React 18 Strict Mode.
      const videoElement = document.createElement("video-js");

      videoElement.classList.add("vjs-big-play-centered");
      videoRef.current.appendChild(videoElement);

      const player = (playerRef.current = videojs(videoElement, options, () => {
        videojs.log("player is ready");
        onReady && onReady(player);
        // setTimeout(() => {
        //     player.play();
        //     console.log("play");
        //   }, 10000);
      }));

      // You could update an existing player in the `else` block here
      // on prop change, for example:
    } else {
      const player = playerRef.current;

      player.autoplay(options.autoplay);
      player.src(options.sources);
    }
  }, [options, videoRef]);

  // Dispose the Video.js player when the functional component unmounts
  React.useEffect(() => {
    const player = playerRef.current;

    return () => {
      if (player && !player.isDisposed()) {
        player.dispose();
        playerRef.current = null;
      }
    };
  }, [playerRef]);

  return (
    <div data-vjs-player>
      <div ref={videoRef} />
    </div>
  );
};

export default VideoJS;
```

![enact-trouble](https://github.com/enactjs/enact/assets/108803279/746174ed-6d84-43b2-a4e8-d8ec5ade66ac)

**Comment by C17AN** [comment]
I'm not an enact developer, but I came across the issue and tried debugging it.

**[Symptoms]**

The problematic part is that if semicolons are used within the src:url() syntax of the CSS, the `postcss-resolution-independence` plug-in appears to fail.

**[Causes]**

The `postcss-resolution-independence` plugin traverses the CSS Node, attempting to recognize phrases such as `src:url(data:application/font-woff; charset=utf-8;base64...` as CSS grammar.

**[Proposal]**

- To resolve the issue quickly, you can modify the `package.json` of the project as follows.

```
"enact": {
"theme": "sandstone",
// Disable postcss-resolution-independence plug-in
"ri": false
},
```

- I think css line which starts with "data:" should be added as a whitelist to the `unknownWord()` function of `postcss-values-pacer`, but unfortunately I'm not sure.

I hope it helped you.

**Comment by Hmelevschi1980** [comment]
thank you! it is working
