### ISSUE TITLE
Unable to play google video ads in Video Player

### ISSUE THREAD

**Issue by arulkumararul2000** [enactjs/enact#3245]
### Video player

* [ ] Google Video Ads integration
* [ ] Video Ads in Pre, Mid and Post video.

### Description
By pass the vast url and based on that url google video ads need to play [You can also refer this](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags#vmap-session-ad-rule-pre-roll) 

### Comments
I have try so many way but no use please help me out

**Comment by vJIYEv** [comment]
Hello @arulkumararul2000, Thank you for your report.
I will check this issue and let you know the result soon.

**Comment by vJIYEv** [comment]
Hello, @arulkumararul2000.
I made a video player sample that plays a google video ad: https://github.com/enactjs/samples/pull/236
This sample follows google IMA SDK tutorial and is adjusted to Enact video player.

To integrate google video ads in Enact video player,
1. import the IMA SDK.

```
useEffect(() => {
	const script = document.createElement('script');
	script.src = "https://imasdk.googleapis.com/js/sdkloader/ima3.js";
	document.body.appendChild(script);
	return () => {
		document.body.removeChild(script);
	};
}, []);
```

2. create an ad container with video element of the Enact video player.
```
import VideoPlayer from '@enact/sandstone/VideoPlayer';

const adDisplayContainer = useRef(null);
const adsRef = useRef(null);
const videoRef = useRef(null);

const videoElement = videoRef.current.getVideoNode().media;
adDisplayContainer.current = new window.google.ima.AdDisplayContainer(adsRef.current, videoElement);
```
```
<div>
	<div ref={adsRef} />
	<VideoPlayer ref={videoRef} >
		<source src={source} type="video/mp4" />
		<MediaControls />
	</VideoPlayer>
</div>
```

For more information, please read [README.md](https://github.com/enactjs/samples/tree/1d031f5680bfadc7d16ed85a55d98d15d9339192/sandstone/pattern-video-player-google-ads) and [App.js](https://github.com/enactjs/samples/blob/1d031f5680bfadc7d16ed85a55d98d15d9339192/sandstone/pattern-video-player-google-ads/src/App/App.js) codes in the sample.
