### ISSUE TITLE
Enact pack command doesn't build project to es5 and that cause errors at older TVs

### ISSUE THREAD

**Issue by javadsalman** [enactjs/enact#3262]
### Description
Enact pack and pack -p commands doesn't convert final bundle to ES5. It cause render errors at Older TV versions such as webOS TV 4.x (2018-2019).

### Environment
LG Smart TV (2018-2019) and Chromium 53 on Windows

**Enact version:** latest

### Reproduction Code
I got this code pieces from main.js file In dist after run ```npm run pack -p``` command. Which is not supported by older chromium versions
```js
  async resolveData(signal) {
    let aborted = false;
    if (!this.done) {
      let onAbort = () => this.cancel();
      signal.addEventListener("abort", onAbort);
      aborted = await new Promise(resolve => {
        this.subscribe(aborted => {
          signal.removeEventListener("abort", onAbort);
          if (aborted || this.done) {
            resolve(aborted);
          }
        });
      });
    }
    return aborted;
  }

class AbortedDeferredError extends Error {}

const defer = function defer(data, init) {
  if (init === void 0) {
    init = {};
  }
  let responseInit = typeof init === "number" ? {
    status: init
  } : init;
  return new DeferredData(data, responseInit);
};
```

### Comments and Screen Shots
The webpack and babel configuration must be modified to build project to es5 to make it supported by any devices.

**Comment by hong6316** [comment]
Older TV versions cannot supports the latest version of enact.
Please check the below link and choose the appropriate version of enact, then your code will be worked.
https://webostv.developer.lge.com/develop/guides/enyo-enact-guide

**Comment by javadsalman** [comment]
> Older TV versions cannot support the latest version of enact. Please check the below link and choose the appropriate version of enact, and please test again. https://webostv.developer.lge.com/develop/guides/enyo-enact-guide

Thanks for your response. But 2018-2019 is not a long time ago. And I need it to be supported by both new and old devices. Not just older devices. On the other hand, I used a bunch of new features of the latest Enact. It must be parsed to ES5 instead of ES6 to ensure it works smoothly on any device. Or there must be this kind of option to parse to ES5.

**Comment by ahmaaz10** [comment]
Hello I also Have the same issue!
Please fix!

**Comment by hong6316** [comment]
If so, try one of the 2 options:

1. Please try `export ES5="true"`
Whether to force transpiling to full ES5, rather than ES6 targetted to webOS Chrome version.

2. Please try `enact transpile` before `enact pack -p`
This command transpiles the code to ES5.

**Comment by ji394sfx87** [comment]
I use `react-redux` and `@reduxjs/toolkit` with latest version, but it still has ES5 problem.

.browserslistrc setting:
```
> 1%
not chrome < 38
ie >= 11
```

And I build with this: `ES5=true NODE_PATH=./node_modules enact pack -p --content-hash`

I use old version and it can be work in ES5
```
react-redux@7.2.9
@reduxjs/toolkit@1.6.0
```

I think enact does not transpile node_modules code to ES5...

PS: My enact version is `4.7.9`

**Comment by hong6316** [comment]
OK, Thanks for the additional information.
I will check again.

**Comment by javadsalman** [comment]
To overcome this issue without waiting for it to be fixed officially I used this way: It worked for me.

webpack.config.js:
```js
const path = require('path');

module.exports = {
  entry: './dist/main.js',
  output: {
    filename: './main.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
    ]
  },
  mode: 'production'
};
```
.babelrc
```js
{
	"presets": [
	  ["@babel/preset-env", {
		"useBuiltIns": "usage",
		"corejs": 3
	  }]
	]
  }
  ```
  
  index.js
  ```js
  import 'abortcontroller-polyfill';
import {createRoot, hydrateRoot} from 'react-dom/client';
import './index.css'
import App from './App';
...
```

package.json
```js
"devDependencies": {
		"@babel/core": "^7.25.2",
		"@babel/preset-env": "^7.25.3",
		"autoprefixer": "^10.4.19",
		"babel-loader": "^9.1.3",
		"css-loader": "^7.1.2",
		"eslint-config-enact-proxy": "^1.0.7",
		"webpack-cli": "^5.1.4"
	}
"dependencies": {
"core-js": "^3.37.1",
"abortcontroller-polyfill": "^1.7.5"
}
....
```

I modified the pack command to enact pack -p && npx webpack.
Webpack parses the bundled main.js to ES5 and the issues disappear.
This way can be used as a temporary method.

**Comment by hong6316** [comment]
To transpile to ES5, including node module code, enter the command below.
This is how to transpile the code after the bundle is completed.
```shell
$ enact pack -o=result
$ enact transpile
(The built results are in "(your project)/build/result".)
``` 

※ `enact transpile` does not transpile the `dist` folder, so please specify the name with the -o option when running `enact pack`. (We will discuss whether to fix this.)

However, please use this only when transpiling to ES5 is necessary.

**Comment by javadsalman** [comment]
> Hi @javadsalman I would appreciate your telling me which app you are developing. I am very interested in seeing your app in webOS TV :) I also hope to hong's guide will work for you. Thanks.

Hi @seunghoh. Your interest made me happy. The app is at the QA stage of the LG Store. When it is ready, I'm gonna send the reference from the store and will give you a premium account to be able to take a look.

**Comment by ji394sfx87** [comment]
> To overcome this issue without waiting for it to be fixed officially I used this way: It worked for me.
> 
> webpack.config.js:
> 
> ```js
> const path = require('path');
> 
> module.exports = {
>   entry: './dist/main.js',
>   output: {
>     filename: './main.js',
>     path: path.resolve(__dirname, 'dist')
>   },
>   module: {
>     rules: [
>       {
>         test: /\.js$/,
>         exclude: /node_modules/,
>         use: {
>           loader: 'babel-loader'
>         }
>       },
>     ]
>   },
>   mode: 'production'
> };
> ```
> 
> .babelrc
> 
> ```js
> {
> 	"presets": [
> 	  ["@babel/preset-env", {
> 		"useBuiltIns": "usage",
> 		"corejs": 3
> 	  }]
> 	]
>   }
> ```
> 
> index.js
> 
> ```js
> import 'abortcontroller-polyfill';
> import {createRoot, hydrateRoot} from 'react-dom/client';
> import './index.css'
> import App from './App';
> ...
> ```
> 
> package.json
> 
> ```js
> "devDependencies": {
> 		"@babel/core": "^7.25.2",
> 		"@babel/preset-env": "^7.25.3",
> 		"autoprefixer": "^10.4.19",
> 		"babel-loader": "^9.1.3",
> 		"css-loader": "^7.1.2",
> 		"eslint-config-enact-proxy": "^1.0.7",
> 		"webpack-cli": "^5.1.4"
> 	}
> "dependencies": {
> "core-js": "^3.37.1",
> "abortcontroller-polyfill": "^1.7.5"
> }
> ....
> ```
> 
> I modified the pack command to enact pack -p && npx webpack. Webpack parses the bundled main.js to ES5 and the issues disappear. This way can be used as a temporary method.

Hi @javadsalman 
I tried your solution, but show this error in 
```js
ERROR in [eslint] 
src/index.jsx
  Line 0:  Parsing error: Cannot find module '@babel/preset-env'
```
Did you meat this error before? How to resolve?

**Comment by javadsalman** [comment]
@seunghoh Hello. I hope you're doing well. Our application is ready and on the LG Store. We would be happy to give a premium account to you to check out our app if you'd provide email address.

**Comment by seunghoh** [comment]
Sounds great! So happy to hear that. My mail is hohpark at gmail.com. Can't wait to see your awesome application.

**Comment by javadsalman** [comment]
@seunghoh I'd like to inform you that I sent. You can check your inbox. Best regards

**Comment by seunghoh** [comment]
Hi @javadsalman I've got email and confirmed the link in the mail. It redirects to the metaflix site. What's next? Should I register the new account with the same email address?

**Comment by seunghoh** [comment]
@javadsalman Got it! Now it works :) I am so excited to explore your app on webOS TV! Thanks~~
