### ISSUE TITLE
Sandstone Video Player with embed audio & subtitle track switcher 

### ISSUE THREAD

**Issue by officialmmt** [enactjs/enact#3269]
### Category
* [ x] Modification of existing component or feature

### Description
Hi, I trying to make a video player able to play any kind of video type from a URL source and able to switch audio & subtitle built-in(embed) tracks. I made many searches and I found some but not a best solution. It will be like VLC player.

**Comment by vJIYEv** [comment]
Hello, @officialmmt
Could you please write more detail of what you make?
I want to know what are the features "like VLC player".

**Comment by vJIYEv** [comment]
@officialmmt ,
We have a sample app pattern which supports m3u8 video type and subtitles in Enact Sandstone video player: https://github.com/enactjs/samples/tree/develop/sandstone/pattern-video-player-custom
This sample demonstrates how to add and play custom videos in the Enact Sandstone video player.
I think you can add custom features that you want to your own video player with reference to this pattern.
Please check if the sample code can help you. Thank you.

**Comment by seunghoh** [comment]
HI @officialmmt If the sample can't solve your problem, would help to reproduce your problem? (such as URLs that we can try) 
For your information, if you are making the app for webOS, you don't have to customize enact video player for hls file. It supports from the webOS system. https://webostv.developer.lge.com/develop/guides/mediaoption-parameter#MediaTransportTypes 
Finally, I am so interested in you making the app for webOS and Tizen both with Enact. Can you introduce me your app more? and Please let me know when your app is on webOS app store.

**Comment by vJIYEv** [comment]
Close this issue as inactive
