### ISSUE TITLE
Spotlight direction events needs improvment

### ISSUE THREAD

**Issue by javadsalman** [enactjs/enact#3276]
### Description
Let's say there are 4 sandstone spottable buttons and they are placed vertically. And you wanna When the user presses the down key from Button 1, the spotlight focuses on Button 3. But this time, the spotlight focuses on another element which is directly under the wished target. And in this situation, this target element is Button 3 but the spotted element is Button 4. It must focus on Button 3 but it focuses on Button 4. I don't know if is it really a bug but I think there must be a way to handle this process manually. By the way, if I use onBlur event instead of onSpotlightDown everything works well but this time you can't choose the required direction (it's down in this case).
```js
<Button id="button-1" onSpotlightDown={() => Spotlight.focus('#button-3')}>Button 1</Button>
<Button id="button-2">Button 2</Button>
<Button id="button-3">Button 3</Button>
<Button id="button-4">Button 4</Button>
```

### Environment:
Microsoft Edge, Webos Emulator, LG Smart TV

**Enact version: 4.7.8**

**Comment by juwonjeong** [comment]
Hi, @javadsalman. Thanks for reporting the issue.
In your case, we believe that you need to add ev.stopPropagation() in `onSpotlightDown` handler to stop the default focus handling of the spotlight.

`<Button id="button-1" onSpotlightDown={
    (ev) => {
        Spotlight.focus('#button-3');
	ev.stopPropagation();
}}>Button 1</Button>`

**Comment by javadsalman** [comment]
I thought I already tried this method but had missed it. Now it works for me. Thanks!
